name = "vmess"
main = "_worker.js"
compatibility_date = "2023-05-26"
# node_compat = true
workers_dev = true

[vars]
# PROXYIP = "43.218.77.16:443"
UUID = "131be127-64db-43b9-89c8-30a2c5f5e9a0"
# SOCKS5 = "127.0.0.1:1080"
# SOCKS5_RELAY = "true"
